let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Casual Shirt",
    price: 4500,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Shirt",
    price: 1000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "T-Shirt",
    price: 2500,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Mens Suit",
    price: 3000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-4.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Mens Tie",
    price: 2005,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-5.png",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Casual Shoes",
    price: 2000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-6.png",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Black Suit",
    price: 4500,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-7.png",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Polo Shirt",
    price: 4500,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-8.png",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Denim Shirt",
    price: 8005,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-9.png",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Denim Pants",
    price: 1020,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-10.png",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "Basic Cap",
    price: 3500,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-11.png",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Leather Boots",
    price: 3500,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-12.png",
  },
];